// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniSystem.Data;

#nullable disable

namespace UniSystem.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniSystem.Data.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Faculty of Engineering",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Faculty of Arts and Humanities",
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Faculty of Business and Economics",
                            UniversityId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Faculty of Medicine",
                            UniversityId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Faculty of Computer Science",
                            UniversityId = 2
                        });
                });

            modelBuilder.Entity("UniSystem.Data.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            Name = "Mechanical Engineering"
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 2,
                            Name = "English Literature"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 3,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 4,
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = 5,
                            FacultyId = 5,
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("UniSystem.Data.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "National University of Science and Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "International Business and Technology University"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Global Medical University"
                        });
                });

            modelBuilder.Entity("UniSystem.Data.Models.Faculty", b =>
                {
                    b.HasOne("UniSystem.Data.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("UniSystem.Data.Models.Major", b =>
                {
                    b.HasOne("UniSystem.Data.Models.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniSystem.Data.Models.Faculty", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("UniSystem.Data.Models.University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
